name: App workflow
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      App1:
        description: 'App1' 
        required: true 
      App2:
        description: 'App2' 
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  printInputs:
   runs-on: ubuntu-latest
   steps:
    - run: |
        echo "App1: ${{ github.event.inputs.App1 }}""
        echo "App2: ${{ github.event.inputs.App2 }}""
  App1:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy App1
      if: github.event.inputs.App1 == 'App1'
      run: echo "Hello ${{ github.event.inputs.App1 }}"
  App2:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy App2
      if: github.event.inputs.App2 == 'App2'
      run: echo "Hello ${{ github.event.inputs.App2 }}"
